### PR TITLE
175 support maria db

### PR DESCRIPTION
**Pull request by adityakukankar**
#175 - Added integration tests for MariaDB.

### CODE REVIEW

**Comment by adityakukankar** [comment]
Hi @kdhrubo, I have added the integration tests for MariaDB. There are 5 tests failing. I was not able to figure out the root cause (still looking into it), tests are similar to mysql and postgres tests. 

I was getting these exceptions:
1) `Error: 1064-42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'lang_4 WHERE lang_4.name = 'ENGLISH'' at line 2` in MariaDBDeleteControllerTest.

2) `com.jayway.jsonpath.PathNotFoundException: No results for path: $['keys']['GENERATED_KEY']` in MariaDBCreateControllerTest.

If you have ever encountered these exception before please guide me here.

**Comment by kdhrubo** [comment]
Did you merge your code with v 0.3.0 master ?

**Comment by adityakukankar** [comment]
Yes it is updated. I can see v 0.3.0 in the pom.

**Review by kdhrubo — APPROVED** [review]
Looks good

**Pull request merged**
